version: "3.8"

services:
  leazy-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1810:3000"
    environment:
      - PORT=3001
      - FLAG=SENTRIX{BotClientSid3ReqForgery}
      - AUTHORIZED_IP=47.245.121.0
