version: '3'

services:
  web-warmupheadache:
    build:
      context: src
  
    restart: always
    networks:
      - internal
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 2111:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
  bot:
    build:
      context: bot
      args:
        - BROWSER=chromium
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://proxy/
      APPURLREGEX: ^http(|s)://proxy/.*$
      APPFLAG: SENTRIX{this_1s_1ntend33d_n0t_l1k3_pr0j3ct_s3k410ne}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
      # for wayland display
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}

    networks:
      - internal
      # uncoment this if you need to run the bot in GUI mode
      # run this before running the docker container if you're use xauth `sudo xhost +local:docker`

    # volumes:
    #   # - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY # for wayland
    #   - /tmp/.X11-unix:/tmp/.X11-unix # for xorg

networks:
  internal:
